USE DATABASE INSURANCE_DB;
USE SCHEMA INSURANCE_CURATED;

CREATE OR REPLACE TABLE CUSTOMER_DIM (
  CUSTOMER_KEY NUMBER AUTOINCREMENT,
  CUSTOMER_ID NUMBER,
  FIRST_NAME STRING,
  LAST_NAME STRING,
  EMAIL STRING,
  PHONE_NUMBER STRING,
  DATE_OF_BIRTH DATE,
  ADDRESS STRING,
  EFFECTIVE_DATE DATE,
  EXPIRY_DATE DATE,
  CURRENT_FLAG STRING,
  CREATED_AT TIMESTAMP
);

CREATE OR REPLACE TABLE POLICY_DIM (
  POLICY_KEY NUMBER AUTOINCREMENT,
  POLICY_ID NUMBER,
  CUSTOMER_ID NUMBER,
  POLICY_TYPE STRING,
  POLICY_START_DATE DATE,
  POLICY_END_DATE DATE,
  PREMIUM_AMOUNT NUMBER(10, 2),
  POLICY_STATUS STRING,
  UPDATED_AT TIMESTAMP,
);