USE DATABASE INSURANCE_DB;
USE SCHEMA INSURANCE_CURATED;

CREATE OR REPLACE TABLE CLAIM_FACT (
  CLAIM_KEY NUMBER AUTOINCREMENT,
  CLAIM_ID NUMBER,
  POLICY_KEY NUMBER,
  CUSTOMER_KEY NUMBER,
  POLICY_ID NUMBER,
  CUSTOMER_ID NUMBER,
  CLAIM_DATE DATE,
  CLAIM_AMOUNT NUMBER(10,2),
  CLAIM_STATUS STRING,
  CLAIM_DESCRIPTION STRING,
  LOAD_TIMESTAMP TIMESTAMP
);