MERGE INTO INSURANCE_CURATED.POLICY_DIM AS TARGET
USING INSURANCE_ODS.POLICY_ODS AS SOURCE
ON TARGET.POLICY_ID = SOURCE.POLICY_ID
WHEN MATCHED THEN
    UPDATE SET 
        TARGET.CUSTOMER_ID = SOURCE.CUSTOMER_ID,
        TARGET.POLICY_TYPE = SOURCE.POLICY_TYPE,
        TARGET.POLICY_START_DATE = SOURCE.POLICY_START_DATE,
        TARGET.POLICY_END_DATE = SOURCE.POLICY_END_DATE,
        TARGET.PREMIUM_AMOUNT = SOURCE.PREMIUM_AMOUNT,
        TARGET.POLICY_STATUS = SOURCE.POLICY_STATUS,
        TARGET.UPDATED_AT = CURRENT_TIMESTAMP()

WHEN NOT MATCHED THEN
    INSERT (
        POLICY_ID, 
        CUSTOMER_ID, 
        POLICY_TYPE, 
        POLICY_START_DATE, 
        POLICY_END_DATE, 
        PREMIUM_AMOUNT, 
        POLICY_STATUS, 
        UPDATED_AT
    )
    VALUES (
        SOURCE.POLICY_ID, 
        SOURCE.CUSTOMER_ID, 
        SOURCE.POLICY_TYPE, 
        SOURCE.POLICY_START_DATE, 
        SOURCE.POLICY_END_DATE, 
        SOURCE.PREMIUM_AMOUNT, 
        SOURCE.POLICY_STATUS, 
        CURRENT_TIMESTAMP()
    );