//UPDATE EXISTING RECORDS//

UPDATE INSURANCE_CURATED.CUSTOMER_DIM AS TARGET
SET 
    CURRENBT_FLAG = 'N',
    EXPIRY_DATE = CURRENT_DATE()
FROM INSURNCE_ODS.CUSTOMER_ODS AS SOURCE
WHERE TARGET.CUSTOMER_ID = SOURCE.CUSTOMER_ID
AND TARGET.CURRENT_FLAG = 'Y'
AND (
    TARGET.FIRST_NAME <> SOURCE.FIRST_NAME OR
    TARGET.LAST_NAME <> SOURCE.LAST_NAME OR
    TARGET.EMAIL <> SOURCE.EMAIL OR
    TARGET.ADDRESS <> SOURCE.ADDRESS
);



//INSERT NEW VERSION//

INSERT INTO INSURANCE_CURATED.CUSTOMER_DIM (
    CUSTOMER_ID, 
    FIRST_NAME, 
    LAST_NAME, 
    EMAIL, 
    PHONE_NUMBER, 
    DATE_OF_BIRTH, 
    ADDRESS, 
    EFFECTIVE_DATE, 
    EXPIRY_DATE, 
    CURRENT_FLAG,
    CREATED_AT
)SELECT 
    SOURCE.CUSTOMER_ID, 
    SOURCE.FIRST_NAME, 
    SOURCE.LAST_NAME, 
    SOURCE.EMAIL, 
    SOURCE.PHONE_NUMBER, 
    SOURCE.DATE_OF_BIRTH, 
    ADDRESS, 
    CURRENT_DATE(), 
    '9999-12-31', 
    'Y',
    CURRENT_TIMESTAMP()
FROM INSURANCE_ODS.CUSTOMER_ODS AS SOURCE
LEFT JOIN INSURANCE_CURATED.CUSTOMER_DIM AS TARGET
ON SOURCE.CUSTOMER_ID = TARGET.CUSTOMER_ID
AND TARGET.CURRENT_FLAG = 'Y'
WHERE TARGET.CUSTOMER_ID IS NULL
OR (
    TARGET.FIRST_NAME <> SOURCE.FIRST_NAME OR
    TARGET.LAST_NAME <> SOURCE.LAST_NAME OR
    TARGET.EMAIL <> SOURCE.EMAIL OR
    TARGET.ADDRESS <> SOURCE.ADDRESS
);