INSERT INTO INSURANCE_CURATED.CLAIM_FACT (
    CLAIM_ID,
    POLICY_KEY,
    CUSTOMER_KEY, 
    POLICY_ID,
    CUSTOMER_ID, 
    CLAIM_DATE, 
    CLAIM_AMOUNT, 
    CLAIM_STATUS, 
    CLAIM_DESCRIPTION, 
    LOAD_TIMESTAMP
)
SELECT 
    C.CLAIM_ID,
    P.POLICY_KEY,
    D.CUSTOMER_KEY,
    C.POLICY_ID,
    P.CUSTOMER_ID,
    C.CLAIM_DATE,
    C.CLAIM_AMOUNT,
    C.CLAIM_STATUS,
    C.CLAIM_DESCRIPTION,
    CURRENT_TIMESTAMP()
FROM INSURANCE_ODS.CLAIM_ODS C
INNER JOIN INSURANCE_CURATED.POLICY_DIM P ON C.POLICY_ID = P.POLICY_ID
INNER JOIN INSURANCE_CURATED.CUSTOMER_DIM D ON P.CUSTOMER_ID = D.CUSTOMER_ID
WHERE D.CURRENT_FLAG = 'Y';