USE DATABASE INSURANCE_DB;

CREATE OR REPLACE SCHEMA INSURANCE_RAW;

CREATE OR REPLACE SCHEMA INSURANCE_STAGING;

CREATE OR REPLACE SCHEMA INSURANCE_ODS;

CREATE OR REPLACE SCHEMA INSURANCE_CURATED;

CREATE OR REPLACE SCHEMA INSURANCE_AUDIT;