USE DATABASE INSURANCE_DB;
USE SCHEMA INSURANCE_STAGING;

CREATE OR REPLACE TABLE CUSTOMER_STAGING (
  CUSTOMER_ID NUMBER,
  FIRST_NAME STRING,
  LAST_NAME STRING,
  EMAIL STRING,
  PHONE_NUMBER STRING,
  DATE_OF_BIRTH DATE,
  ADDRESS STRING,
  CREATED_AT TIMESTAMP
);

