USE DATABASE INSURANCE_DB;
USE SCHEMA INSURANCE_RAW;

CREATE OR REPLACE FILE FORMAT INSURANCE_CSV_FILE_FORMAT
  TYPE = 'CSV'
  SKIP_HEADER = 1
  FIELD_DELIMITER = ','
  FIELD_OPTIONALLY_ENCLOSED_BY = '"'
  NULL_IF = ('NULL', 'null', '');