USE DATABASE INSURANCE_DB;
USE SCHEMA INSURANCE_RAW;

CREATE OR REPLACE STAGE CUSTOMER_STAGE
  FILE_FORMAT = INSURANCE_CSV_FILE_FORMAT;

CREATE OR REPLACE STAGE POLICY_STAGE
  FILE_FORMAT = INSURANCE_CSV_FILE_FORMAT;

CREATE OR REPLACE STAGE CLAIM_STAGE
  FILE_FORMAT = INSURANCE_CSV_FILE_FORMAT;

CREATE OR REPLACE STAGE PAYMENT_STAGE
  FILE_FORMAT = INSURANCE_CSV_FILE_FORMAT;

CREATE OR REPLACE STAGE PROVIDER_STAGE
  FILE_FORMAT = INSURANCE_CSV_FILE_FORMAT;