USE ROLE ACCOUNTADMIN;
USE DATABASE INSURANCE_DB;
USE SCHEMA INSURANCE_RAW;

CREATE OR REPLACE TABLE CUSTOMER_RAW (
  CUSTOMER_ID NUMBER,
  FIRST_NAME STRING,
  LAST_NAME STRING,
  EMAIL STRING,
  PHONE_NUMBER STRING,
  DATE_OF_BIRTH DATE,
  ADDRESS STRING,
  CREATED_AT TIMESTAMP,
);


CREATE OR REPLACE TABLE POLICY_RAW (
  POLICY_ID NUMBER,
  CUSTOMER_ID NUMBER,
  POLICY_TYPE STRING,
  POLICY_START_DATE DATE,
  POLICY_END_DATE DATE,
  PREMIUM_AMOUNT NUMBER(10, 2),
  POLICY_STATUS STRING,
);

CREATE OR REPLACE TABLE CLAIM_RAW (
  CLAIM_ID NUMBER,
  POLICY_ID NUMBER,
  CLAIM_DATE DATE,
  CLAIM_AMOUNT NUMBER(10, 2),
  CLAIM_STATUS STRING,
  CLAIM_DESCRIPTION STRING,
);

CREATE OR REPLACE TABLE PAYMENT_RAW (
  PAYMENT_ID NUMBER,
  CLAIM_ID NUMBER,
  PAYMENT_DATE DATE,
  PAYMENT_AMOUNT NUMBER(10, 2),
  PAYMENT_METHOD STRING,
);


CREATE OR REPLACE TABLE PROVIDER_RAW (
  PROVIDER_ID NUMBER,
  PROVIDER_NAME STRING,
  PROVIDER_TYPE STRING,
  CITY STRING,
  STATE STRING,
);