USE DATABASE INSURANCE_DB;
USE SCHEMA INSURANCE_RAW;

COPY INTO CUSTOMER_RAW
FROM @CUSTOMER_STAGE
FILE_FORMAT = (FORMAT_NAME = INSURANCE_CSV_FILE_FORMAT);


COPY INTO POLICY_RAW
FROM @POLICY_STAGE
FILE_FORMAT = (FORMAT_NAME = INSURANCE_CSV_FILE_FORMAT);

COPY INTO CLAIM_RAW
FROM @CLAIM_STAGE
FILE_FORMAT = (FORMAT_NAME = INSURANCE_CSV_FILE_FORMAT);