USE DATABASE INSURANCE_DB;
USE SCHEMA INSURANCE_ODS;

CREATE OR REPLACE TABLE CUSTOMER_ODS (
  CUSTOMER_ID NUMBER,
  FIRST_NAME STRING,
  LAST_NAME STRING,
  EMAIL STRING,
  PHONE_NUMBER STRING,
  DATE_OF_BIRTH DATE,
  ADDRESS STRING,
  CREATED_AT TIMESTAMP,
  UPDATED_AT TIMESTAMP
);