USE DATABASE INSURANCE_DB;
USE SCHEMA INSURANCE_ODS;

CREATE OR REPLACE TABLE CUSTOMER_ODS (
  CUSTOMER_ID NUMBER,
  FIRST_NAME STRING,
  LAST_NAME STRING,
  EMAIL STRING,
  PHONE_NUMBER STRING,
  DATE_OF_BIRTH DATE,
  ADDRESS STRING,
  CREATED_AT TIMESTAMP,
  UPDATED_AT TIMESTAMP
);

CREATE OR REPLACE TABLE POLICY_ODS (
  POLICY_ID NUMBER,
  CUSTOMER_ID NUMBER,
  POLICY_TYPE STRING,
  POLICY_START_DATE DATE,
  POLICY_END_DATE DATE,
  PREMIUM_AMOUNT NUMBER(10, 2),
  POLICY_STATUS STRING,
  UPDATED_AT TIMESTAMP
);


CREATE OR REPLACE TABLE CLAIM_ODS (
  CLAIM_ID NUMBER,
  POLICY_ID NUMBER,
  CLAIM_DATE DATE,
  CLAIM_AMOUNT NUMBER(10, 2),
  CLAIM_STATUS STRING,
  CLAIM_DESCRIPTION STRING,
  UPDATED_AT TIMESTAMP
);


