USE DATABASE INSURANCE_DB;

MERGE INTO INSURANCE_ODS.CUSTOMER_ODS AS TARGET
USING INSURANCE_STAGING.CUSTOMER_STAGING AS SOURCE
ON TARGET.CUSTOMER_ID = SOURCE.CUSTOMER_ID
WHEN MATCHED THEN
    UPDATE SET 
        TARGET.FIRST_NAME = SOURCE.FIRST_NAME,
        TARGET.LAST_NAME = SOURCE.LAST_NAME,
        TARGET.EMAIL = SOURCE.EMAIL,
        TARGET.PHONE_NUMBER = SOURCE.PHONE_NUMBER,
        TARGET.DATE_OF_BIRTH = SOURCE.DATE_OF_BIRTH,
        TARGET.ADDRESS = SOURCE.ADDRESS,
        TARGET.UPDATED_AT = CURRENT_TIMESTAMP()

WHEN NOT MATCHED THEN
    INSERT (
        CUSTOMER_ID, 
        FIRST_NAME, 
        LAST_NAME, 
        EMAIL, 
        PHONE_NUMBER, 
        DATE_OF_BIRTH, 
        ADDRESS, 
        CREATED_AT,
        UPDATED_AT
    )
    VALUES (
        SOURCE.CUSTOMER_ID, 
        SOURCE.FIRST_NAME, 
        SOURCE.LAST_NAME, 
        SOURCE.EMAIL, 
        SOURCE.PHONE_NUMBER, 
        SOURCE.DATE_OF_BIRTH, 
        SOURCE.ADDRESS, 
        SOURCE.CREATED_AT,
        CURRENT_TIMESTAMP()
    );


-----------------------------------------------------------------------------------------------------------------------------------------------------------------------

MERGE INTO INSURANCE_ODS.POLICY_ODS AS TARGET
USING INSURANCE_STAGING.POLICY_STAGING AS SOURCE
ON TARGET.POLICY_ID = SOURCE.POLICY_ID
WHEN MATCHED THEN
    UPDATE SET 
        TARGET.POLICY_TYPE = SOURCE.POLICY_TYPE,
        TARGET.PREMIUM_AMOUNT = SOURCE.PREMIUM_AMOUNT,
        TARGET.POLICY_STATUS = SOURCE.POLICY_STATUS,
        TARGET.UPDATED_AT = CURRENT_TIMESTAMP()
WHEN NOT MATCHED THEN
    INSERT (
        POLICY_ID,
        CUSTOMER_ID,
        POLICY_TYPE,
        POLICY_START_DATE,
        POLICY_END_DATE,
        PREMIUM_AMOUNT,
        POLICY_STATUS,
        UPDATED_AT
    )
    VALUES (
        SOURCE.POLICY_ID,
        SOURCE.CUSTOMER_ID,
        SOURCE.POLICY_TYPE,
        SOURCE.POLICY_START_DATE,
        SOURCE.POLICY_END_DATE,
        SOURCE.PREMIUM_AMOUNT,
        SOURCE.POLICY_STATUS,
        CURRENT_TIMESTAMP()
    );
