USE DATABASE INSURANCE_DB;

MERGE INTO INSURANCE_ODS.CUSTOMER_ODS AS TARGET
USING INSURANCE_STAGING.CUSTOMER_STAGING AS SOURCE
ON TARGET.CUSTOMER_ID = SOURCE.CUSTOMER_ID
WHEN MATCHED THEN
    UPDATE SET 
        TARGET.FIRST_NAME = SOURCE.FIRST_NAME,
        TARGET.LAST_NAME = SOURCE.LAST_NAME,
        TARGET.EMAIL = SOURCE.EMAIL,
        TARGET.PHONE_NUMBER = SOURCE.PHONE_NUMBER,
        TARGET.DATE_OF_BIRTH = SOURCE.DATE_OF_BIRTH,
        TARGET.ADDRESS = SOURCE.ADDRESS,
        TARGET.UPDATED_AT = CURRENT_TIMESTAMP()

WHEN NOT MATCHED THEN
    INSERT (
        CUSTOMER_ID, 
        FIRST_NAME, 
        LAST_NAME, 
        EMAIL, 
        PHONE_NUMBER, 
        DATE_OF_BIRTH, 
        ADDRESS, 
        CREATED_AT,
        UPDATED_AT
    )
    VALUES (
        SOURCE.CUSTOMER_ID, 
        SOURCE.FIRST_NAME, 
        SOURCE.LAST_NAME, 
        SOURCE.EMAIL, 
        SOURCE.PHONE_NUMBER, 
        SOURCE.DATE_OF_BIRTH, 
        SOURCE.ADDRESS, 
        SOURCE.CREATED_AT,
        CURRENT_TIMESTAMP()
    );